import ProjectDescription

let workspace = Workspace(
    name: "TinyAudioUnitHost",
    projects: [
        "TinyAudioUnitHost",
        "StorageKit",
        "AudioSettingsKit",
        "AudioUnitsKit",
        "EngineKit",
        "PresetKit",
        "Common",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all)
    )
)
